---
title: Korean Conflict
author: Andrew Innes
date: '2017-10-17'
slug: korean-conflict
categories:
  - R
tags:
  - ggplot
  - Time Series
---

Looking at a data set from Kaggle that shows data on the Korean conflict.

First we need to import libraries:

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(lubridate)
```

Then import the data:

```{r}
deaths<-read.csv("KoreanConflict.csv",header=TRUE,stringsAsFactors=FALSE)
# Import the data

colnames(deaths)
# Show the column names
```

Look at the incident dates to see how to find a problem with the data and fix it:

```{r}
sum(str_detect(deaths$INCIDENT_DATE,"\\d{8}"))
# Looks for an 8 digit entry in the column incident date
```

```{r}
for(i in 1:36574){
  # Loop through all the rows
  incident<-str_detect(deaths$INCIDENT_DATE[i],"\\d{8}")
  fatality<-str_detect(deaths$FATALITY[i],"\\d{8}")
  if(!incident & fatality){
    deaths$INCIDENT_DATE[i]<-deaths$FATALITY[i]
  }
}
```

Then sort the data:

```{r}
df<-deaths%>%
  filter(str_detect(deaths$INCIDENT_DATE,"\\d{8}")==TRUE)%>%
  group_by(INCIDENT_DATE)%>%
  summarize(num_deaths=n())%>%
  mutate(date=ymd(INCIDENT_DATE))%>%
  filter(date<="1953-07-27")%>%
  select(INCIDENT_DATE,num_deaths,date)
```

Then graph the data:

```{r}
ggplot()+
  geom_line(data=df,aes(x=date,y=num_deaths))+
  scale_x_date(date_breaks='3 months',date_labels="%b %y")
```

Next lets look at birth years:

```{r}
df <- deaths%>%
  filter(str_detect(deaths$BIRTH_YEAR, "\\d{4}"))%>%
  group_by(BIRTH_YEAR)%>%
  summarise(num_deaths = n())%>%
  mutate(date=(BIRTH_YEAR))%>%
  select(BIRTH_YEAR, num_deaths, date)%>%
  arrange(desc(num_deaths))
```

Then graph it:

```{r}
ggplot()+
  geom_line(data = df, aes(x = BIRTH_YEAR, y = num_deaths, group = 1))+
  coord_flip()
```

